name: InfiniteWorld
main: com.gmail.felix.schmalzel.infiniteworld.InfiniteWorld
version: ${project.version}
api-version: "1.15"
author: Felix Schmalzel
commands:
  IWset:
    description: "This command centers the border on the player, and optionally sets the shape, size and padding. Shapes: circle, square, disabled."
    usage: /IWset [shape] [radius] [bufferzone]